export { default as ProfilePage } from './ProfilePage'
export { default as DashboardPage } from './DashboardPage'
export { default as FilesPage } from './FilesPage'
export { default as EditPage } from './EditPage'
export { default as ViewPage } from './ViewPage'
export { default as CollectionPage } from './CollectionPage'
export { default as NotFoundPage } from './NotFoundPage'
export { default as NewPage } from './NewPage'
